apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-001
  template:
    metadata:
      labels:
        app: test-001
    spec:
      containers:
      - name: test-001
        image: 10.42.0.1:30000/test-image:1.0.0
